package com.example.firstapplication.esmaulhusna.ui

import android.content.Intent
import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity
import androidx.recyclerview.widget.LinearLayoutManager
import com.example.firstapplication.R
import com.example.firstapplication.esmaulhusna.adapter.EsmaulHusnaAdapter
import com.example.firstapplication.esmaulhusna.model.EsmaulHusnaModel
import com.example.firstapplication.esmaulhusna.utill.onEsmaulhusnaClickListener
import kotlinx.android.synthetic.main.activity_esmaul_husna_activity.*
import java.util.*

class esmaul_husna_activity : AppCompatActivity(),
    onEsmaulhusnaClickListener {


    var esmaulHusnaArray = ArrayList<EsmaulHusnaModel>()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_esmaul_husna_activity)


        addarray()


        esmaul_husna_rv.apply {

            layoutManager = LinearLayoutManager(this@esmaul_husna_activity)
            adapter =
                EsmaulHusnaAdapter(
                    this@esmaul_husna_activity,
                    esmaulHusnaArray,
                    this@esmaul_husna_activity
                )


        }


    }


    override fun onesmaulhusnaclick(esmaulhusna: EsmaulHusnaModel) {

        var intent = Intent(this, EsmaulHusnaDetayActivity::class.java)
        var ehimage = intent.putExtra("ehimage", esmaulhusna.image)
        var ehname = intent.putExtra("ehname", esmaulhusna.isim)
        startActivity(intent)

    }


    fun addarray() {


        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.allah,
                "Allah"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.rahman,
                "Er-Rahmân"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.rahim,
                "Er-Rahim"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.melik,
                "El-Melik"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.kuddus,
                "El-Kuddûs"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.selam,
                "Es-Selâm"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.mumin,
                "El-Mü'min"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.muheymin,
                "El-Müheymin"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.aziz,
                "Aziz"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.cebbar,
                "Cebbâr"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.mutekebbir,
                "El-Mütekebbir"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.halik,
                "El-Hâlık"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.bari,
                "Bârî"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.musavvir,
                "El-Musavvir"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.gaffar,
                "El-Gaffâr"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.kahhar,
                "El-Kahhâr"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.vehhab,
                "El-Vehhâb"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.rezzak,
                "Er-Rezzâk"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.fettah,
                "El-Fettâh"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.alim,
                "El-Alîm"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.kabid,
                "El-Kâbıd"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.basit,
                "El-Bâsıt"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.hafid,
                "El-Hâfıd"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.rafi,
                "Er-Râfî"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.muizz,
                "El-Muiz"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.muzil,
                "El-Muzil"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.semi,
                "Es-Semî"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.basir,
                "El-Basîr"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.hakem,
                "El-Hakem"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.adl,
                "El-Adl"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.latif,
                "El-Latîf"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.habir,
                "El-Habîr"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.halim,
                "El-Halîm"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.azim,
                "El-Azîm"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.gafur,
                "El-Gafûr"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.sekur,
                "Eş-Şekûr"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.aliyy,
                "El-Aliyy"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.kebir,
                "El-Kebîr"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.hafiz,
                "El-Hafîz"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.mukit,
                "El-Mukît"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.hasib,
                "El-Hasîb"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.celil,
                "El-Celîl"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.kerim,
                "El-Kerîm"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.rakib,
                "Er-Rakîb"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.mucib,
                "El-Mücîb"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.vasi,
                "El-Vâsî"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.hakim,
                "El-Hakîm"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.vedud,
                "El-Vedûd"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.mecid,
                "El-Mecîd"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.bais,
                "El-Bâis"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.sehid,
                "Eş-Şehîd"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.hakk,
                "El-Hakk"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.vekil,
                "El-Vekîl"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.kaviyy,
                "El-Kaviyy"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.metin,
                "El-Metîn"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.veli,
                "El-Veliyy"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.hamid,
                "El-Hamîd"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.muhsi,
                "El-Muhsî"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.mubdi,
                "El-Mübdi"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.muid,
                "El-Muid"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.muhyi,
                "El-Muhyî"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.mumit,
                "El-Mümît"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.hayy,
                "El-Hayy"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.kayyum,
                "El-Kayyûm"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.vacid,
                "El-Vâcid"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.macid,
                "El-Mâcid"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.vahid,
                "El-Vâhid"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.samed,
                "Es-Samed"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.kadir,
                "El-Kâdir"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.muktedir,
                "El-Muktedir"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.mukaddim,
                "El-Mukaddim"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.muahhir,
                "El-Muahhir"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.evvel,
                "El-Evvel"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.ahir,
                "El-Âhir"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.zahir,
                "Ez-Zâhir"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.batin,
                "El-Bâtın"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.vali,
                "El-Vâlî"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.muteali,
                "El-Müteâlî"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.berr,
                "El-Berr"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.tevvab,
                "Et-Tevvâb"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.muntekim,
                "El-Müntakim"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.afuvv,
                "El-Afüvv"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.rauf,
                "El-Rauf"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.malikulmulk,
                "Mâlikü’l-Mülk"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.zulcelalivelikram,
                "Zü’l- Celal-i ve’l-İkram"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.muksit,
                "El-Muksıt"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.cami,
                "El-Câmî"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.ganiyy,
                "El-Ganîyy"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.mugni,
                "El-Muğnî"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.mani,
                "El-Mânî"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.carr,
                "Ed-Dâr"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.nafi,
                "En-Nâfi"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.nur,
                "En-Nûr"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.hadi,
                "El-Hâdî"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.bedi,
                "El-Bedî"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.baki,
                "El-Bâki"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.varis,
                "El-Vâris"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.resid,
                "Er-Reşid"
            )
        )
        esmaulHusnaArray.add(
            EsmaulHusnaModel(
                R.drawable.sabur,
                "Es-Sabûr"
            )
        )


    }


}
